"""Add checks repr column

Revision ID: 57aee30d211d
Revises: 611fe6b37106
Create Date: 2025-02-17 18:34:03.065912

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '57aee30d211d'
down_revision = '611fe6b37106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checks', sa.Column('repr', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checks', 'repr')
    # ### end Alembic commands ###
