"""Add extra indices

Revision ID: 611fe6b37106
Revises: dd5d6172aa23
Create Date: 2025-02-17 18:32:18.802332

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '611fe6b37106'
down_revision = 'dd5d6172aa23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_checks_creator_payment_method_date', 'checks', ['creator_id', 'payment_method', 'created_at'], unique=False)
    op.create_index('idx_checks_creator_total_amount_date', 'checks', ['creator_id', 'total_amount', 'created_at'], unique=False)
    op.create_index('idx_checks_creator_total_amount_date_payment_method', 'checks', ['creator_id', 'total_amount', 'created_at', 'payment_method'], unique=False)
    op.create_index(op.f('ix_checks_payment_method'), 'checks', ['payment_method'], unique=False)
    op.create_index(op.f('ix_checks_total_amount'), 'checks', ['total_amount'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checks_total_amount'), table_name='checks')
    op.drop_index(op.f('ix_checks_payment_method'), table_name='checks')
    op.drop_index('idx_checks_creator_total_amount_date_payment_method', table_name='checks')
    op.drop_index('idx_checks_creator_total_amount_date', table_name='checks')
    op.drop_index('idx_checks_creator_payment_method_date', table_name='checks')
    # ### end Alembic commands ###
