---
name: Build
on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Lint & Security Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Test Check App
        run: docker compose build check-app-test-base
      - name: Run Linting
        run: |
          docker compose run --rm check-app-test-base sh -c "flake8 . && isort --check --diff . && mypy . && yamllint ."
      - name: Run Security Analysis
        run: |
          docker compose run --rm check-app-test-base bandit -r .
