---
name: Build and Release
on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint_and_security:
    name: Lint & Security Checks
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pull-requests: read
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Test Check App
        run: docker compose build check-app-test-base

      - name: Run Linting
        run: |
          docker compose run --rm check-app-test-base sh -c "flake8 . && isort --check --diff . && yamllint ."
          # docker compose run --rm check-app-test-base sh -c "flake8 . && isort --check --diff . && mypy . && yamllint ."

      - name: Run Security Analysis
        run: |
          docker compose run --rm check-app-test-base bandit -r .
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
